/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 .\public\assets\chat_bubble_icon\scene.gltf -o .\app\components\homePageComponent\ChatBuble.jsx -r .\public\assets\chat_bubble_icon\ 
Author: AnshiNoWara (https://sketchfab.com/AnshiNoWara)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chat-bubble-icon-d13ff0267030497ca91742ba011b0829
Title: Chat Bubble Icon
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

// @ts-ignore
export function ChatBubble(props) {
  // @ts-ignore
  const { nodes, materials } = useGLTF("/assets/chat_bubble_icon/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials["Material.002"]}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials["Material.003"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/assets/chat_bubble_icon/scene.gltf");
