/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 .\public\assets\emoji_heart_message\scene.gltf -o .\app\components\homePageComponent\Heart.jsx -r .\public\assets\emoji_heart_message\ 
Author: i.deal3d (https://sketchfab.com/i.deal3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/emoji-heart-message-4bc8a62a1a1942b3a9ad74e60cf575d5
Title: Emoji heart message
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

// @ts-ignore
export function HeartIcon(props) {
  // @ts-ignore
  const { nodes, materials } = useGLTF(
    "/assets/emoji_heart_message/scene.gltf"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials["Material.016"]}
        position={[0.003, 0.695, 0.069]}
        rotation={[0, 0, -0.776]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.Material}
        position={[0.003, 0.72, 0.023]}
      />
    </group>
  );
}

useGLTF.preload("/assets/emoji_heart_message/scene.gltf");
