/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 .\public\assets\winking_face_emoji\scene.gltf -o .\app\components\homePageComponent\WinkinngFaceIcon.jsx -r .\public\assets\winking_face_emoji\ 
Author: i.deal3d (https://sketchfab.com/i.deal3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/winking-face-emoji-fd6858bf813042cbb22e19f13ce1012d
Title: Winking face emoji
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

// @ts-ignore
export function WinkinngFaceIcon(props) {
  // @ts-ignore
  const { nodes, materials } = useGLTF("assets/winking_face_emoji/scene.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[-0.003, 0, -0.001]} rotation={[-Math.PI / 2, 0.004, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.016, 0.722, 0.135]}>
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials["Material.009"]}
            />
            <mesh
              geometry={nodes.Object_5.geometry}
              material={materials["Material.013"]}
            />
          </group>
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials["Material.013"]}
            position={[-0.023, 0.716, 0.255]}
            rotation={[0.032, 0, 0]}
          />
          <mesh
            geometry={nodes.Object_9.geometry}
            material={materials["Material.013"]}
            position={[-0.047, 0.762, 0.239]}
            rotation={[1.334, 0.659, 0.258]}
          />
          <mesh
            geometry={nodes.Object_11.geometry}
            material={materials["Material.013"]}
            position={[0.059, 0.706, 0.254]}
            rotation={[0.015, 0.21, -1.574]}
          />
          <mesh
            geometry={nodes.Object_13.geometry}
            material={materials["Material.013"]}
            position={[0.075, 0.74, 0.251]}
            rotation={[1.314, -0.001, -0.423]}
          />
          <mesh
            geometry={nodes.Object_15.geometry}
            material={materials.Material}
            position={[0.009, 0.724, 0.117]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/winking_face_emoji/scene.gltf");
